/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ICliConfig {
  ethereum: {
    /**
     * Network endpoint URL
     */
    endpoint: string;
    /**
     * Directory where contract deployment lock files stored
     */
    lockfilesDir: string;
    /**
     * Network from address
     */
    from: string;
    /**
     * Default Gas limit
     */
    gas: string;
    /**
     * Default Gas price
     */
    gasPrice: string;
    /**
     * Biometrids token contract
     */
    BiometridsToken?: {
      /**
       * Path to the contract schema
       */
      schema: string;
      /**
       * Address for deployed Token contract
       */
      instance?: string;
      [k: string]: any;
    };
    /**
     * Ico stages pricing strategy contract
     */
    IcoStagesPricingStrategy?: {
      /**
       * Path to the contract schema
       */
      schema: string;
      [k: string]: any;
    };
    /**
     * Crowd sale refund vault contract
     */
    CrowdSaleRefundVault?: {
      /**
       * Path to the contract schema
       */
      schema: string;
      /**
       * wallet
       */
      wallet?: string;
      [k: string]: any;
    };
    /**
     * Crowd sale contract
     */
    CrowdSale?: {
      /**
       * Path to the contract schema
       */
      schema: string;
      [k: string]: any;
    };
    /**
     * Ico finalize agent contract
     */
    IcoFinalizeAgent?: {
      /**
       * Path to the contract schema
       */
      schema: string;
      [k: string]: any;
    };
    [k: string]: any;
  };
  [k: string]: any;
}
